FROM sygryd-base:latest

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
            curl \
            openssh-client \
            docker && \
    rm -rf /var/lib/apt/lists/*

RUN bash -euo pipefail -c "curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh  | sh -s -- -b /usr/local/bin"
RUN bash -euo pipefail -c "curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin"

COPY src/sygryd-backend.py      /app

CMD ["python", "sygryd-backend.py"]

